module.exports = {
  // babel: {
  //   asyncToPromises: true,
  //   babelrc: false,
  //   configFile: false,
  //   jsx: 'react',
  //   minimal: false,
  //   objectAssign: 'myAssign',
  // },
  banner: false,
  bundleNodeModules: true,
  // env: {},
  // extendConfig: () => {},
  // extendRollupConfig: () => {},
  // externals: [],
  globals: {
    vue: 'Vue',
    'countup.js': 'CountUp',
  },
  input: 'src/countup.vue',
  output: {
    dir: 'dist',
    extractCSS: false,
    // fileName: '[name][suffix].js',
    format: ['cjs-min', 'es-min', 'umd-min'],
    minify: true,
    moduleName: 'VueCountUp',
    sourceMap: true,
    sourceMapExcludeSources: true,
    target: 'browser',
  },
  plugins: {
    vue: true,
  },
  // resolvePlugins: {},
};
